### ISSUE TITLE
Settings changed are skipped

### ISSUE THREAD

**Issue by jaywhy13** [lafarer/ansible-role-osx-defaults#14]
Thanks for the package, this may likely not be an issue but rather my limited knowledge of Ansible. Whichever, I'm unable to get the settings to make the changes to my mac. 

My playbook looks like this:

```yaml
---
- hosts: all

  vars_files:
    - default.config.yml

 roles:
      - { role: lafarer.osx-defaults }
```

And my `default.config.yml`.

```yaml
Configure_Bluetooth: yes
Bluetooth_ShowInMenuBar: no
target_user_id: '<my_username>'
```

The relevant portion of the output:
```
TASK [lafarer.osx-defaults : Bluetooth - Show Bluetooth in menu bar] *************************************************************************************************************************************************************
skipping: [127.0.0.1]
```

It keeps skipping the Bluetooth section even though I have manually turned on the Bluetooth menu from settings. 

![image](https://user-images.githubusercontent.com/779782/103024497-f4e5c880-451d-11eb-90bf-bf39769028a1.png)

I did a check to make sure that the `ansible_user_id` matches the `target_user_id` as well. 

I noticed two other things that may or may not be related:

- Does Ansible auto-discover handlers in the `handlers` directory? I didn't see where the handlers were defined explicitly like the `handlers` section in this [guide](https://docs.ansible.com/ansible/latest/user_guide/playbooks_handlers.html#handler-example).
- [This](https://github.com/lafarer/ansible-role-osx-defaults/blob/132a9d7e3970fcc0a29abf71990a987217454d63/tasks/bluetooth.yml#L10) checks if `Bluetooth_ShowInMenuBar is true` but it seems that we need to cast strings to bool as shown [here](https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html#conditionals-based-on-variables). 

I'm running Ansible 2.10.4.
